### ISSUE TITLE
What is the best source for drug design?

### ISSUE THREAD

**Issue by baonguyen124** [baonguyen124/AI4DrugDesignn#1]
What is the best source for drug design?

**Comment by ngmsonn** [comment]
Github:
https://github.com/asarigun/awesome-denovo-papers

**Comment by baonguyen124** [comment]
> Github: https://github.com/asarigun/awesome-denovo-papers

thanks

**Comment by ngmsonn** [comment]
https://github.com/xnuohz/awesome-drug-discovery

**Comment by baonguyen124** [comment]
<3
